name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ""
          - os: windows
            arch: amd64
            ext: ".exe"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.9'

    - name: Build binary
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o chat-tui-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} -ldflags="-s -w" ./main.go

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: chat-tui-${{ matrix.os }}-${{ matrix.arch }}
        path: chat-tui-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifacts/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}